# Generated by Django 4.2.6 on 2023-10-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Accounts',
        ),
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Purchases',
        ),
    ]
