# Generated by Django 4.2.6 on 2023-11-11 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0003_rename_accounts_account_rename_items_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('AddressId', models.AutoField(primary_key=True, serialize=False)),
                ('AddressStreet', models.CharField(max_length=20)),
                ('AddressCity', models.CharField(max_length=20)),
                ('AddressCountry', models.CharField(max_length=20)),
                ('AddressStreetNumber', models.PositiveIntegerField()),
                ('AddressPostalCode', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='AccountAddressCity',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountAddressCountry',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountAddressPostalCode',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountAddressStreet',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountAddressStreetNumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountBirthDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountEmail',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountPassword',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
