# Generated by Django 4.2.7 on 2023-11-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0004_address_account_accountaddresscity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('ComplaintId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Submit_date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Closed')], default=0)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='OmniShopApp.account')),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OmniShopApp.item')),
            ],
        ),
    ]
