# Generated by Django 4.2.7 on 2023-12-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0006_itemcategory_item_itemdetails_item_itemprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='CategoryId',
            new_name='ItemCategoryId',
        ),
        migrations.RenameField(
            model_name='itemcategory',
            old_name='CategoryName',
            new_name='ItemCategoryName',
        ),
    ]
