# Generated by Django 4.2.7 on 2023-12-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0007_rename_categoryid_itemcategory_itemcategoryid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ItemCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OmniShopApp.itemcategory'),
            preserve_default=False,
        ),
    ]
