# Generated by Django 4.2.7 on 2023-12-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0008_item_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemDetails',
            field=models.CharField(max_length=1000),
        ),
    ]
