# Generated by Django 4.2.7 on 2023-12-11 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0009_alter_item_itemdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OmniShopApp.purchase'),
        ),
        migrations.AddField(
            model_name='item',
            name='ItemRating',
            field=models.FloatField(help_text='Average rating', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ItemSeller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OmniShopApp.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='ItemState',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Second-Hand')], default=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Closed')], default=1),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ReviewText', models.CharField(max_length=1000)),
                ('Submit_date', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OmniShopApp.item')),
                ('Reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OmniShopApp.account')),
            ],
        ),
    ]
