# Generated by Django 4.2.7 on 2023-12-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0010_complaint_purchase_item_itemrating_item_itemseller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='OmniShopApp.item'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='OmniShopApp.account'),
        ),
    ]
