# Generated by Django 4.2.7 on 2023-12-14 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OmniShopApp', '0012_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
