# Generated by Django 4.2.7 on 2023-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0015_account_accountpoints_account_accountvouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='ItemCategoryImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='CustomDrawing',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Sent to Post Office'), (3, 'In Delivery'), (4, 'Delivered')], default=1),
        ),
    ]
