# Generated by Django 4.2.7 on 2023-12-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0016_itemcategory_itemcategoryimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Following',
            field=models.ManyToManyField(to='OmniShopApp.account'),
        ),
    ]
