# Generated by Django 4.2.7 on 2023-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0017_account_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Wishlist',
            field=models.ManyToManyField(null=True, to='OmniShopApp.item'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Following',
            field=models.ManyToManyField(null=True, to='OmniShopApp.account'),
        ),
    ]
