# Generated by Django 4.2.7 on 2023-12-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0020_purchase_purchasecity_purchase_purchasecountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='PurchaseStreet',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
