# Generated by Django 4.2.7 on 2023-12-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OmniShopApp', '0021_alter_purchase_purchasestreet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
